\NeedsTeXFormat{LaTeX2e}[1995/12/01]
\ProvidesClass{jupyterBook}[2020/11/06]

\RequirePackage{xcolor}
\RequirePackage[utf8]{inputenc}
\RequirePackage{graphicx}
\RequirePackage{amsmath}
\RequirePackage{mathrsfs}

\def\sphinxdocclass{report}
\LoadClass{sphinxmanual}

\setlength{\textwidth}{17.5cm}
\setlength{\textheight}{22cm}

\DeclareMathOperator*{\argmax}{arg\,max}
\DeclareMathOperator*{\argmin}{arg\,min}
\DeclareMathOperator*{\gt}{>}
