comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]

coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 0.5%
    patch:
      default:
        target: 80%
        threshold: 0.5%
